### ISSUE TITLE
Validate datetime correctly

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/record-editor#151]
Client side validation complains about the datetime format.

<img width="856" alt="screen shot 2017-06-26 at 6 19 35 pm" src="https://user-images.githubusercontent.com/580727/27549467-52aad246-5a9c-11e7-9654-b41d3d750b63.png">

**Comment by zzacharo** [comment]
@jmartinm do we want specific format? I omitted from https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/328 because we don't want to restrict date-time field in inspire. If this is a problem I can add a specific format to the previous PR. But on `inspire-next` we allow date-time on it's default behaviour.

**Comment by zzacharo** [comment]
I checked how ajv handles `date-time` and actually as you can see here https://github.com/epoberezkin/ajv/blob/fde7030a19833273b08e8de879cb2bf149adaf2f/spec/extras/%24data/format.json#L28 only `rfc3339` are valid formats and here is the applied regex https://github.com/epoberezkin/ajv/blob/fde7030a19833273b08e8de879cb2bf149adaf2f/lib/compile/formats.js#L36. This means that appending a `Z` in the end of the above value corrects the error. Also, I checked `jsonschema` package that is used in server side and here https://github.com/Julian/jsonschema/blob/v2.3.0/jsonschema/_format.py#L169 you can see that tries to import `strict_rfc3339` and if fails then uses isodate. If `rfc3339` is valid then the above value gives also an error in server-side validation. Currently because we don't have this package the `isodate` module accepts this format. @jmartinm @michamos what do you propose to do? I can reuse the regex that is internally used and change the part with the `Z` char and in server-side as we don't install `strict_rfc3339` we are consistent.

**Comment by michamos** [comment]
Parsing dates with regexes like this is suboptimal, as you cannot catch the fact that some months have 30 days and so on. There should be something like [`the python datetime module`](https://docs.python.org/2/library/datetime.html#datetime.datetime.strptime) in JS, that can read a date-time in a specified format, and checks that it is actually valid:
```
In [1]: from datetime import datetime

In [2]: datetime.strptime('2017-02-29','%Y-%m-%d')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-ba3cbc992f57> in <module>()
----> 1 datetime.strptime('2017-02-29','%Y-%m-%d')

/usr/lib/python2.7/_strptime.pyc in _strptime(data_string, format)
    456         # Need to add 1 to result since first day of the year is 1, not 0.
    457         julian = datetime_date(year, month, day).toordinal() - \
--> 458                   datetime_date(year, 1, 1).toordinal() + 1
    459     else:  # Assume that if they bothered to include Julian day it will
    460            # be accurate.

ValueError: day is out of range for month
```

**Comment by zzacharo** [comment]
After merging this PR https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/328 in `ng2-json-editor`  the `date-time` will have the z suffix in the end optional and so we can configure `record-editor` accordingly. Still missing the check for valid date-ranges (e.g set day a value `45`) but this only will happen in client side as at server we support this check.
