### ISSUE TITLE
Proposal for a new editor

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/record-editor#2]
After investigating and trying existing solutions (#1) and prototyping 2 approaches, we decided to build a new editor from scratch.
# record-editor
## Idea

Idea is to have simple and compact UI which is similar to BibEdit, but will have more features. To achieve this, we will flatten the JSON schema so that it will not be more nested than MARC format (`field.subField.value`). The other important difference in the UI is representation of arrays will be like tables.
### Screen shot from the prototype

![screen shot 2016-06-15 at 08 55 04](https://cloud.githubusercontent.com/assets/4868667/16070611/04f249f0-32d7-11e6-8688-7004f55bda2b.png)
## Features
- Auto completion for almost all fields
- Customizing (?)
  - Users can load a config file to configure shortcut keys, field orders, some parts of UI.
- Easy navigation to fields (`scrollspy` )
- Large array handling (>100)
- Raw editing
- Schema validation
## Technologies
- Angular 2
- Webpack
- TypeScript
- SCSS (SASS 3)

**Comment by jmartinm** [comment]
Other features
============

- Integration with PDF view - side by side with editor
- Rich autocompletion for linked references
    - For example author field will suggest from the existing authors in the database
    - A conference paper will allow to link to the correct conference (and allow creation of new one if non-existing)
- Autocompletion from configurable list of values or from ES (using search API)
- Easy plugin of features to manipulate the record
    - Examples:
        - A button that when clicked extracts references from the attached PDF, shows a preview and on accept adds them to the record.
        - A button that on clicked will extract the keywords and add them to the record
        - Management of files inside the record
        - Future integration with ticketing system (like RT)
        - Integration with history of a record
        - (this will be using existing APIs to perform the operations on the record and then updating the UI)
- Template for the record
    - Based on the schema. There should be a hint of what possible fields can be filled in the opened record.
        - Possible (important) fields that are not currently filled can be displayed with an empty input so that a cataloger knows that they need to be filled.
- Rule based validation
    - Validation of the record based on custom functions
        - Example: If Language: French is filled it is mandatory to fill the Translated title field
- Get a preview of how the record will look like once submitted
- All modifications should be saved automatically (so that in case of window closing no data is lost)
- Possibility to merge a record in the interface
    - Given any second JSON - and with the output of the existing JSON-merger, display in the interface the conflicts and approve/reject (see https://github.com/inspirehep/json-merger)
- Links to external identifiers: arXiv id points to the arXiv page, DOI field points to the dx.doi.org resolver, URLs are clickable
- Create a record from scratch (from a given source) - paste a DOI, an arXiv id or a CDS number and prefill the form to create a new record.
- Automatically tag cataloger changes
    - Add a flag curated_flag=True to field so that automatic tools don’t overwrite those changes.
- Easy reordering of lists (drag&drop)

**Comment by kaplun** [comment]
> A conference paper will allow to link to the correct conference (and allow creation of new one if non-existing)

How are you envisioning "allowing creation of new one" to be? Like a redirect? Should deposit become something that fits in a widget? Should it open an other editor?
