### ISSUE TITLE
UI error when nothing found in Search

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#251]
When no search results are found, the record editor should stay in the previous page, as it correctly does in some cases:
<img width="628" alt="screen shot 2017-11-15 at 14 22 27" src="https://user-images.githubusercontent.com/24955201/32838634-e42e8976-ca11-11e7-930e-28adeecf5dd2.png">

Instead, sometimes when you search, you get an empty record editor. That needs to be fixed:
<img width="1337" alt="screen shot 2017-11-15 at 14 15 21" src="https://user-images.githubusercontent.com/24955201/32838628-e1a2398c-ca11-11e7-92e6-c1d0d0144605.png">

**Comment by harunurhan** [comment]
For me it is always showing blank page when nothing is found, but user can always go back to the same one.

if we stay on same record, I thought it would confuse users that somehow search was successful and this was result. Because of the current consistent client-side router implementation it's also not as easy as it seems, to make it like the otherwise.

@StellaCh ?
